name: Register User Positions

on:
  schedule:
    # Run every 6 minutes
    - cron: "*/6 * * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  register-positions:
    runs-on: ubuntu-latest

    steps:
      - name: Call Register Positions API
        run: |
          curl -X GET \
            -H "x-api-key: ${{ secrets.API_KEY }}" \
            ${{ secrets.API_URL }}/register-all-users-position
